{{- if .Values.api.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ecommerce-cs-agent.apiServiceAccountName" . }}
  labels:
    {{- include "ecommerce-cs-agent.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
automountServiceAccountToken: {{ .Values.api.serviceAccount.automount }}
{{- end }}
